package config

object ConfigServerRequest {
    const val USER_CHARACTERS_LIST_REQUEST = "USER_CHARACTERS_LIST_REQUEST"
    const val USER_STARTERS_LIST_REQUEST = "USER_STARTERS_LIST_REQUEST"

    const val GAME_MAP_CHECKSUM = "GAME_MAP_CHECKSUM"
    const val GAME_MAP = "GAME_MAP"
}