package config

object ConfigClientRequest {

    const val USER_STARTERS_LIST_REQUEST = "USER_STARTERS_LIST_REQUEST"
    const val USER_CHARACTERS_LIST_REQUEST = "USER_CHARACTERS_LIST_REQUEST"
    const val USER_SELECT_CHARACTER_REQUEST = "USER_SELECT_CHARACTER_REQUEST"
    const val USER_CREATE_CHARACTER_REQUEST = "USER_CREATE_CHARACTER_REQUEST"
    const val USER_DELETE_CHARACTER_REQUEST = "USER_DELETE_CHARACTER_REQUEST"
}