package config

object ConfigClientRequest {

    val USER_STARTERS_LIST_REQUEST = "USER_STARTERS_LIST_REQUEST"
    val USER_CHARACTERS_LIST_REQUEST = "USER_CHARACTERS_LIST_REQUEST"
    val USER_CREATE_CHARACTER_REQUEST = "USER_CREATE_CHARACTER_REQUEST"
    val USER_DELETE_CHARACTER_REQUEST = "USER_DELETE_CHARACTER_REQUEST"
}